name: CardGames
main: net.punchtree.cardgames.CardGamesPlugin
version: 1.0.1
api-version: 1.19
depend: [MapManager, BKCommonLib]
author: Cxom
website: www.punchtree.net
description: Card Games in Minecraft

commands:
    cardgames:
        aliases: cg
    cardtabletest:
    createcardtable:
    vanillamaptesting: